# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_wnd.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.g_dsb = QtWidgets.QDoubleSpinBox(Form)
        self.g_dsb.setSuffix("")
        self.g_dsb.setDecimals(6)
        self.g_dsb.setMinimum(9.8)
        self.g_dsb.setMaximum(10.0)
        self.g_dsb.setSingleStep(0.01)
        self.g_dsb.setProperty("value", 10.0)
        self.g_dsb.setObjectName("g_dsb")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.g_dsb)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.is_animated_chb = QtWidgets.QCheckBox(Form)
        self.is_animated_chb.setText("")
        self.is_animated_chb.setChecked(True)
        self.is_animated_chb.setObjectName("is_animated_chb")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.is_animated_chb)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.graph_time_dsb = QtWidgets.QDoubleSpinBox(Form)
        self.graph_time_dsb.setDecimals(1)
        self.graph_time_dsb.setMinimum(1.0)
        self.graph_time_dsb.setMaximum(10.0)
        self.graph_time_dsb.setSingleStep(0.5)
        self.graph_time_dsb.setProperty("value", 2.0)
        self.graph_time_dsb.setObjectName("graph_time_dsb")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.graph_time_dsb)
        self.save_btn = QtWidgets.QPushButton(Form)
        self.save_btn.setObjectName("save_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.save_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Настройки"))
        self.label.setText(_translate("Form", "Ускорение свободного падения g (м/с2)"))
        self.label_2.setText(_translate("Form", "Анимировать траекторию движения тела"))
        self.label_3.setText(_translate("Form", "Время отрисовки графика (с)"))
        self.save_btn.setText(_translate("Form", "Сохранить и закрыть"))
